# Generated by Django 5.2.5 on 2025-08-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='school_class',
            field=models.CharField(choices=[('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], default='5', max_length=2, verbose_name='Класс'),
        ),
    ]
